fix 26866

diff --git a/cf-template.yaml b/cf-template.yaml
--- a/cf-template.yaml
+++ b/cf-template.yaml
@@ -1,5 +1,6 @@
 AWSTemplateFormatVersion: 2010-09-09
 Description: Vault as KMS replacement PoC.
+
 Resources:
   InstanceSecurityGroup:
     Type: AWS::EC2::SecurityGroup
@@ -31,11 +32,12 @@ Resources:
           unzip vault_0.10.1_linux_amd64.zip -d /usr/local/bin
 
           export VAULT_DEV_ROOT_TOKEN_ID=root
-          export VAULT_ADDR=http://127.0.0.1
+          export VAULT_ADDR=http://127.0.0.1:8200
 
-          systemd-run --unit=vault /usr/local/bin/vault server -dev
+          vault server -dev &
 
           vault secrets enable transit
+          vault auth enable aws
 
       Tags:
       - Key: Name
@@ -72,70 +74,70 @@ Resources:
 
             # if curl pkcs7 fails, exit with error logged
             token_exists () {
-                if [ -f $token_path ]; then
-                    return 0
-                else
-                    return 1
-                fi
+              if [ -f $token_path ]; then
+                return 0
+              else
+                return 1
+              fi
             }
 
             token_is_valid() {
-                #  https://www.vaultproject.io/api/auth/token/index.html#lookup-a-token-self-
-                echo "Checking token validity"
-                token_lookup=$(curl \
-                    --request GET \
-                    --header "X-Vault-Token: $(cat $token_path)" \
-                    --write-out %{http_code} \
-                    --silent \
-                    --output /dev/null \
-                    http://${VaultIP}:8200/v1/auth/token/lookup-self)
-                if [ "$token_lookup" == "200" ]; then
-                    echo "$0 - Valid token found, exiting"
-                    return 0
-                else
-                    echo "$0 - Invalid token found"
-                    return 1
-                fi
+              #  https://www.vaultproject.io/api/auth/token/index.html#lookup-a-token-self-
+              echo "Checking token validity"
+              token_lookup=$(curl \
+                --request GET \
+                --header "X-Vault-Token: $(cat $token_path)" \
+                --write-out %{http_code} \
+                --silent \
+                --output /dev/null \
+                http://${VaultIP}:8200/v1/auth/token/lookup-self)
+              if [ "$token_lookup" == "200" ]; then
+                echo "$0 - Valid token found, exiting"
+                return 0
+              else
+                echo "$0 - Invalid token found"
+                return 1
+              fi
             }
 
             main () {
-                if ! token_exists; then
-                    aws_login ""
-                elif token_exists && ! token_is_valid; then
-                    aws_login "$(cat $nonce_path)"
-                else
-                    logger $0 "current vault token is still valid"
-                    exit 0
-                fi
+              if ! token_exists; then
+                aws_login ""
+              elif token_exists && ! token_is_valid; then
+                aws_login "$(cat $nonce_path)"
+              else
+                logger $0 "current vault token is still valid"
+                exit 0
+              fi
             }
 
             aws_login () {
-                pkcs7=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')
-                if [ -z "$1" ]; then
-                    # do not load nonce if initial login
-                    login_payload=$(cat <<EOF
+              pkcs7=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')
+              if [ -z "$1" ]; then
+                # do not load nonce if initial login
+                login_payload=$(cat <<EOF
             {
               "role": "test",
-              "pkcs7": "$${pkcs7}"
+              "pkcs7": "$pkcs7"
             }
             EOF
-                )
-                else
+              )
+              else
                 # load nonce in payload for reauthentication
                 login_payload=$(cat <<EOF
             {
               "role": "test",
-              "pkcs7": "$${pkcs7}",
+              "pkcs7": "$pkcs7",
               "nonce": "$1"
             }
             EOF
-                )
-                fi
+              )
+              fi
 
-            curl \
+              curl \
                 --silent \
                 --request POST \
-                --data "$${login_payload}" \
+                --data "$login_payload" \
                 http://${VaultIP}:8200/v1/auth/aws/login | tee \
                 >(jq -r .auth.client_token > $token_path) \
                 >(jq -r .auth.metadata.nonce > $nonce_path)
@@ -145,6 +147,7 @@ Resources:
             SCRIPT
 
           - { VaultIP: !GetAtt VaultInstance.PrivateIp }
+
       Tags:
       - Key: Name
         Value: vault-poc-encrypter
@@ -180,70 +183,70 @@ Resources:
 
             # if curl pkcs7 fails, exit with error logged
             token_exists () {
-                if [ -f $token_path ]; then
-                    return 0
-                else
-                    return 1
-                fi
+              if [ -f $token_path ]; then
+                return 0
+              else
+                return 1
+              fi
             }
 
             token_is_valid() {
-                #  https://www.vaultproject.io/api/auth/token/index.html#lookup-a-token-self-
-                echo "Checking token validity"
-                token_lookup=$(curl \
-                    --request GET \
-                    --header "X-Vault-Token: $(cat $token_path)" \
-                    --write-out %{http_code} \
-                    --silent \
-                    --output /dev/null \
-                    http://${VaultIP}:8200/v1/auth/token/lookup-self)
-                if [ "$token_lookup" == "200" ]; then
-                    echo "$0 - Valid token found, exiting"
-                    return 0
-                else
-                    echo "$0 - Invalid token found"
-                    return 1
-                fi
+              #  https://www.vaultproject.io/api/auth/token/index.html#lookup-a-token-self-
+              echo "Checking token validity"
+              token_lookup=$(curl \
+                --request GET \
+                --header "X-Vault-Token: $(cat $token_path)" \
+                --write-out %{http_code} \
+                --silent \
+                --output /dev/null \
+                http://${VaultIP}:8200/v1/auth/token/lookup-self)
+              if [ "$token_lookup" == "200" ]; then
+                echo "$0 - Valid token found, exiting"
+                return 0
+              else
+                echo "$0 - Invalid token found"
+                return 1
+              fi
             }
 
             main () {
-                if ! token_exists; then
-                    aws_login ""
-                elif token_exists && ! token_is_valid; then
-                    aws_login "$(cat $nonce_path)"
-                else
-                    logger $0 "current vault token is still valid"
-                    exit 0
-                fi
+              if ! token_exists; then
+                aws_login ""
+              elif token_exists && ! token_is_valid; then
+                aws_login "$(cat $nonce_path)"
+              else
+                logger $0 "current vault token is still valid"
+                exit 0
+              fi
             }
 
             aws_login () {
-                pkcs7=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')
-                if [ -z "$1" ]; then
-                    # do not load nonce if initial login
-                    login_payload=$(cat <<EOF
+              pkcs7=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')
+              if [ -z "$1" ]; then
+                # do not load nonce if initial login
+                login_payload=$(cat <<EOF
             {
               "role": "test",
-              "pkcs7": "$${pkcs7}"
+              "pkcs7": "$pkcs7"
             }
             EOF
-                )
-                else
+              )
+              else
                 # load nonce in payload for reauthentication
                 login_payload=$(cat <<EOF
             {
               "role": "test",
-              "pkcs7": "$${pkcs7}",
+              "pkcs7": "$pkcs7",
               "nonce": "$1"
             }
             EOF
-                )
-                fi
+              )
+              fi
 
-            curl \
+              curl \
                 --silent \
                 --request POST \
-                --data "$${login_payload}" \
+                --data "$login_payload" \
                 http://${VaultIP}:8200/v1/auth/aws/login | tee \
                 >(jq -r .auth.client_token > $token_path) \
                 >(jq -r .auth.metadata.nonce > $nonce_path)
@@ -253,6 +256,7 @@ Resources:
             SCRIPT
 
           - { VaultIP: !GetAtt VaultInstance.PrivateIp }
+
       Tags:
       - Key: Name
         Value: vault-poc-decrypter
